### ISSUE TITLE
Redundant classes in synthetic data

### ISSUE THREAD

**Issue by vishaal27** [Hritikbansal/generative-robustness#2]
Hey, thanks so much for releasing the ImageNet-G-1K datasets (both base-generated and finetuned-generated), this is very useful!
While going through the synthetic dataset, I noticed one anomaly which I thought might be worth flagging. There are two redundant sets of class-names "Sunglasses" and "Missile". These also occur in the original class-names used by the OpenAI folks: https://github.com/openai/CLIP/blob/main/notebooks/Prompt_Engineering_for_ImageNet.ipynb
However, I think the right class-names to synset mappings to use would be `sunglasses: n04356056`, `sunglass: n04355933`, `missile: n03773504` and `projectile: n04008634` (for the full synset-classname mapping, you could check [this](https://raw.githubusercontent.com/vishaal27/SuS-X/main/utils/class_to_synset.py)).
This might therefore lead to some redundancy (although debatable how much of a difference this would make for sunglass vs sunglasses) in both the train and val sets that are generated. It might be worth regenerating the data for the two classes, and see if this improves performance slightly (my hunch is it wouldn't matter too much).

**Comment by Hritikbansal** [comment]
Hi @vishaal27 ,

thanks for reaching out and pointing out this anomaly. I will work on fixing this, however, sometime later since I am busy with some other work. I suggest using the scripts/[colab](https://colab.research.google.com/drive/1I2IO8tD_l9JdCRJHOqlAP6ojMPq_BsoR?usp=sharing) on the GitHub to generate images for the anomalous classes if you want to fix urgently.

I also agree that this will have less effect on the final performance, but good to fix.
